# Wrangler configuration for Imaginary Crime Lab Worker

name = "crime-lab-api"
main = "worker.js"
compatibility_date = "2024-10-25"
compatibility_flags = ["nodejs_compat"]

# Account ID from Cloudflare dashboard
account_id = "0fac1e4324a9b6001e559ee14093caec"

# Environment variables (set via wrangler secret put)
# DO NOT commit actual secrets to this file

[env.production]
name = "crime-lab-api"

[env.production.vars]
SHOPIFY_STORE_DOMAIN = "crime-lab.myshopify.com"

# Development environment
[env.development]
name = "crime-lab-api-dev"

[env.development.vars]
SHOPIFY_STORE_DOMAIN = "crime-lab.myshopify.com"

# Node.js compatibility for @neondatabase/serverless and mongodb
node_compat = true

# Observability
[observability]
enabled = true

# Build configuration
[build]
command = ""
